# Generated by Django 2.2.5 on 2019-11-12 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather_API', '0002_auto_20191112_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather_data',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_API.Location'),
        ),
    ]
